spring.application.name=My first service for integration

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/integration
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver


spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql


external.api.url=http://localhost:8080/Synergy/rest/api/storage/file/get?inline=true&identifier=
external.api.user=postgres
external.api.pass=postgres
